services:
  # ===== Databases =====
  
  cart_redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_auth:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce_auth
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_products:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce_products
    ports:
      - "5433:5432"
    volumes:
      - products_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_products"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_profile:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce_profile
    ports:
      - "5434:5432"
    volumes:
      - profile_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_profile"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo_orders:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_orders_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5




  # ===== Services =====
  auth:
    build: ./services/auth
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce_auth
      POSTGRES_HOST: db_auth
      JWT_SECRET: random-security-secret
      JWT_ALGORITHM: HS256
    depends_on:
      db_auth:
        condition: service_healthy

  cart:
    build: ./services/cart
    restart: always
    ports:
      - "8004:8004"
    environment:
      REDIS_URL: redis://cart_redis:6379/0
      JWT_SECRET: random-security-secret
      JWT_ALGORITHM: HS256
    depends_on:
      cart_redis:
        condition: service_healthy
  products:
    build: ./services/products
    restart: always
    ports:
      - "8002:8002"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce_products
      POSTGRES_HOST: db_products
      JWT_SECRET: random-security-secret
      JWT_ALGORITHM: HS256
    depends_on:
      db_products:
        condition: service_healthy
  
  profile:
    build: ./services/profile
    restart: always
    ports:
      - "8003:8003"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce_profile
      POSTGRES_HOST: db_profile
      JWT_SECRET: random-security-secret
      JWT_ALGORITHM: HS256
    depends_on:
      db_profile:
        condition: service_healthy

  orders:
    build: ./services/orders
    restart: always
    ports:
      - "8001:8001"
    environment:
      MONGO_URL: mongodb://mongo_orders:27017
      MONGO_DB: ecommerce_orders
      JWT_SECRET: random-security-secret
      JWT_ALGORITHM: HS256
    depends_on:
      mongo_orders:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      auth:
        condition: service_started
      products:
        condition: service_started
      profile:
        condition: service_started
      orders:
        condition: service_started

# ===== Volumes =====
volumes:
  auth_db_data:
  products_db_data:
  profile_db_data:
  mongo_orders_data:
